# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Get_Woke!' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Get_Woke!
  pod 'UIView+Shake'
  pod 'SCLAlertView'
  pod 'RxBluetoothKit'

  target 'Get_Woke!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Get_Woke!UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
